// <auto-generated />
using System;
using BookReviewsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookReviewsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702015316_TranslateSeedDataToSpanish")]
    partial class TranslateSeedDataToSpanish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookReviewsApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Category = "Tecnología",
                            PublishedYear = 2008,
                            Summary = "Una guía para escribir código legible y mantenible a través de ejemplos y principios prácticos.",
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt & David Thomas",
                            Category = "Tecnología",
                            PublishedYear = 1999,
                            Summary = "Consejos atemporales que abarcan desde el desarrollo profesional hasta la gestión de proyectos.",
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Yuval Noah Harari",
                            Category = "Historia",
                            PublishedYear = 2011,
                            Summary = "Una breve historia de la humanidad que explora cómo el Homo sapiens llegó a dominar el planeta.",
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Frank Herbert",
                            Category = "Ciencia ficción",
                            PublishedYear = 1965,
                            Summary = "Una épica historia de política, religión y ecología en el planeta desértico Arrakis.",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Patrick Rothfuss",
                            Category = "Fantasía",
                            PublishedYear = 2007,
                            Summary = "La leyenda de Kvothe, un joven huérfano que se convierte en un legendario mago, contada en sus propias palabras.",
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Daniel Kahneman",
                            Category = "No ficción",
                            PublishedYear = 2011,
                            Summary = "Explora los dos sistemas que impulsan la forma en que pensamos y tomamos decisiones.",
                            Title = "Thinking, Fast and Slow"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Gillian Flynn",
                            Category = "Misterio",
                            PublishedYear = 2012,
                            Summary = "Un oscuro thriller psicológico sobre un matrimonio que se vuelve siniestro en un aniversario de bodas.",
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Stephen Hawking",
                            Category = "Ciencia",
                            PublishedYear = 1988,
                            Summary = "La icónica exploración de Hawking sobre el universo, desde el Big Bang hasta los agujeros negros.",
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Walter Isaacson",
                            Category = "Biografía",
                            PublishedYear = 2011,
                            Summary = "La biografía exclusiva del cofundador de Apple, basada en más de cuarenta entrevistas.",
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Douglas Adams",
                            Category = "Ciencia ficción",
                            PublishedYear = 1979,
                            Summary = "Instantes antes de que la Tierra sea demolida para abrir una autopista hiperespacial, Arthur Dent es arrastrado al espacio.",
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        });
                });

            modelBuilder.Entity("BookReviewsApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BookReviewsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookReviewsApi.Models.Review", b =>
                {
                    b.HasOne("BookReviewsApi.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookReviewsApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookReviewsApi.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookReviewsApi.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
