// <auto-generated />
using System;
using BookReviewsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookReviewsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookReviewsApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Category = "Technology",
                            PublishedYear = 2008,
                            Summary = "A guide to writing readable, maintainable code through practical examples and principles.",
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt & David Thomas",
                            Category = "Technology",
                            PublishedYear = 1999,
                            Summary = "Timeless advice covering topics from career development to project management.",
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Yuval Noah Harari",
                            Category = "History",
                            PublishedYear = 2011,
                            Summary = "A brief history of humankind, exploring how Homo sapiens came to dominate the planet.",
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Frank Herbert",
                            Category = "Science Fiction",
                            PublishedYear = 1965,
                            Summary = "An epic tale of politics, religion, and ecology on the desert planet Arrakis.",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Patrick Rothfuss",
                            Category = "Fantasy",
                            PublishedYear = 2007,
                            Summary = "The legend of Kvothe, a young orphan who grows into a legendary wizard, told in his own words.",
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Daniel Kahneman",
                            Category = "Non-Fiction",
                            PublishedYear = 2011,
                            Summary = "Explores the two systems that drive the way we think and make decisions.",
                            Title = "Thinking, Fast and Slow"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Gillian Flynn",
                            Category = "Mystery",
                            PublishedYear = 2012,
                            Summary = "A dark psychological thriller about a marriage that turns sinister on a wedding anniversary.",
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Stephen Hawking",
                            Category = "Science",
                            PublishedYear = 1988,
                            Summary = "Hawking's landmark exploration of the universe, from the Big Bang to black holes.",
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Walter Isaacson",
                            Category = "Biography",
                            PublishedYear = 2011,
                            Summary = "The exclusive biography of Apple's co-founder, based on more than forty interviews.",
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Douglas Adams",
                            Category = "Science Fiction",
                            PublishedYear = 1979,
                            Summary = "Moments before Earth is demolished for a hyperspace bypass, Arthur Dent is swept into space.",
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        });
                });

            modelBuilder.Entity("BookReviewsApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BookReviewsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookReviewsApi.Models.Review", b =>
                {
                    b.HasOne("BookReviewsApi.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookReviewsApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookReviewsApi.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookReviewsApi.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
